// sitio-react/src/components/supermarket-filter.tsx
import React from "react";
import { Button } from "src/components/ui/button";
import { SOURCES, SUPERMARKET_NAMES } from "src/lib/state";
import { useLocation } from "@tanstack/react-router";
import SupermarketLogo from "./supermarket-logo";

interface SupermarketFilterProps {
  selectedSupermarket: string | null;
  onSelect: (supermarket: string | null) => void;
}

const SupermarketFilter: React.FC<SupermarketFilterProps> = ({
  selectedSupermarket,
  onSelect,
}) => {
  const location = useLocation();
  const showChangomas = new URLSearchParams(location.search).has(
    "showChangomas"
  );

  const filteredSources = SOURCES.filter((source) => {
    if (showChangomas) return true;
    return source !== "changomas";
  });

  return (
    <div className="grid w-full grid-cols-3 gap-2">
      <div className="col-span-3 flex justify-center">
        <Button
          variant={!selectedSupermarket ? "default" : "outline"}
          size="sm"
          className="w-2/3 rounded-full"
          onClick={() => onSelect(null)}
        >
          Todos
        </Button>
      </div>
      {filteredSources.map((source) => (
        <Button
          key={source}
          variant={selectedSupermarket === source ? "default" : "outline"}
          size="sm"
          className="rounded-full gap-2 flex items-center justify-center"
          onClick={() => onSelect(source)}
        >
          <SupermarketLogo
            source={source}
            small={true}
            containerClassName="flex-shrink-0"
            className="h-4 max-w-[16px] md:h-5 md:max-w-[20px]"
          />
          <span className="truncate">{SUPERMARKET_NAMES[source]}</span>
        </Button>
      ))}
    </div>
  );
};

export default SupermarketFilter;

// sitio/src/lib/components/supermarket-filter.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import { Filter } from 'lucide-svelte';
	import { SOURCES, SUPERMARKET_NAMES } from '$lib';
	import { createEventDispatcher } from 'svelte';
	import { page } from '$app/stores';
	export let selectedSupermarket: string | null = null;

	const SHOW_CHANGOMAS = new URL($page.url).searchParams.get('showChangomas');

	const dispatch = createEventDispatcher<{
		select: string | null;
	}>();

	function updateSupermarket(supermarket: string | null) {
		dispatch('select', supermarket);
	}

	$: sources = SOURCES.filter((source) => {
		if (SHOW_CHANGOMAS) return true;
		return source !== 'changomas';
	});
</script>

<div class="grid w-full grid-cols-3 gap-2">
	<div class="col-span-3 flex justify-center">
		<Button
			variant={!selectedSupermarket ? 'default' : 'outline'}
			size="sm"
			class="w-2/3 rounded-full"
			onclick={() => updateSupermarket(null)}
		>
			Todos
		</Button>
	</div>
	{#each sources as source}
		<Button
			variant={selectedSupermarket === source ? 'default' : 'outline'}
			size="sm"
			class="rounded-full"
			onclick={() => updateSupermarket(source)}
		>
			{SUPERMARKET_NAMES[source]}
		</Button>
	{/each}
</div>
